version: '2'
services:
  web:
    build: .
    ports:
      - "8112:3000"
    container_name: projectworks.local
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle/
      - BUNDLE_APP_CONFIG=/usr/local/bundle/
    volumes:
      - .:/opt/service:cached
      - bundle-cache:/usr/local/bundle/
    depends_on:
      - database
      - webpack
      - redis
    command: bin/docker-web
    env_file:
      .env

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/opt/service:cached
    ports:
      - '3035:3000'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  database:
    container_name: projectworks-database.local
    image: postgres:13
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgresql-data: {}
  bundle-cache: {}
  redis_data: {}

